# Generated by Django 4.2.21 on 2025-05-15 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logioca', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='es_vip',
        ),
        migrations.AddField(
            model_name='cliente',
            name='rol',
            field=models.CharField(choices=[('admin', 'Admin'), ('vip', 'VIP'), ('normal', 'No VIP')], default='normal', max_length=10),
        ),
    ]
