# Generated by Django 4.2.21 on 2025-05-17 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logioca', '0004_configuraciondescuento'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='tipo',
            field=models.CharField(default='normal', max_length=20),
        ),
        migrations.AlterField(
            model_name='carrito',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
