# Generated by Django 4.2.21 on 2025-05-18 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logioca', '0005_carrito_tipo_alter_carrito_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='compra_finalizada',
            field=models.BooleanField(default=False),
        ),
    ]
