# Generated by Django 4.2.21 on 2025-05-18 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logioca', '0007_remove_carrito_compra_finalizada'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialVIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logioca.cliente')),
            ],
        ),
    ]
