# Generated by Django 4.2.21 on 2025-05-19 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logioca', '0008_historialvip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuraciondescuento',
            name='monto_descuento',
        ),
        migrations.AddField(
            model_name='configuraciondescuento',
            name='monto_minimo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
