# Generated by Django 4.2.21 on 2025-05-20 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logioca', '0009_remove_configuraciondescuento_monto_descuento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuraciondescuento',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
